---
spring:
  application:
    name: goinmul-api-local
  profiles: local
  datasource:    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  mvc:
    view:
      prefix: "/WEB-INF/jsp/"
      suffix: ".jsp"

logging:
  config: classpath:logback-local.xml
  
privacy:
  crypto:
    use: false

---
spring:
  application:
    name: goinmul-api-dev
  profiles: dev
  mvc:
    view:
      prefix: "/WEB-INF/jsp/"
      suffix: ".jsp"

logging:
  config: classpath:logback-dev.xml

privacy:
  crypto:
    use: false